### ISSUE TITLE
Running Evaluations without merging

### ISSUE THREAD

**Issue by DennisTang2000** [tanganke/fusion_bench#20]
Hello,

Is there a way to run evaluations on just 1 model without merging anything?

For example, Flan-T5 + some LoRA model? I understand that can be specified in the modelpool but what should the method be? technically, it works to use simple averaging (with 1 model only) but is there a more, straight forward way to run the eval?

Thanks!

**Comment by tanganke** [comment]
The [dummy method](https://github.com/tanganke/fusion_bench/blob/08f8abd636b54ffcbce43c95c9c06f6f7671835f/fusion_bench/method/dummy.py#L1-L25) simply returns the first model from the model pool.
