### ISSUE TITLE
Reference for SMILE

### ISSUE THREAD

**Issue by pclucas14** [tanganke/fusion_bench#3]
Hi, 

Congratulations on your new paper SMILE! It's quite interesting. Our team has done very similar work (on creating a post-hoc MoE with a router initialized with the SVD of the finetuned matrix) which was presented at ICML recently. It would be great if you could cite our [paper](https://arxiv.org/abs/2405.11157)!

Thanks :)

**Comment by tanganke** [comment]
Thank you for reaching out and we appreciate your interest in our work. We were not aware of your work at the time of writing, and I'm glad you brought it to our attention. We would be happy to include a reference to your work in future revisions.

**Comment by pclucas14** [comment]
Sure thing. We released a [survey paper](https://arxiv.org/abs/2408.07057) on MoEfication of models if you're interested in checking out relevant work! It includes some of your papers I think
