### ISSUE TITLE
Can't reproduce NYUV2 experiments

### ISSUE THREAD

**Issue by VirtualSpaceman** [tanganke/fusion_bench#46]
**Describe the bug**
Hi, thanks for the amazing work and for making the code publicly available! I can't reproduce the experiment with NYUV2 datasets. I get the following error after running any method [described in the docs](https://tanganke.github.io/fusion_bench/modelpool/nyuv2/):
```
 omegaconf.errors.ConfigAttributeError: Missing key run
    full_key: run
    object_type=dict
```

I would appreciate it if you let me know how to fix this. Thanks! 

**To Reproduce**
```
fusion_bench --config-name nyuv2_config \
    method=task_arithmetic \
        method.scaling_factor=0.3
```

or 

```
fusion_bench --config-name nyuv2_config \
    method=simple_average
```

**Expected behavior**
Run the NYU2 benchmark with ResNet models on segmentation tasks and collect the results. 

**Screenshots**
<img width="875" alt="Screenshot 2024-12-03 at 12 27 12" src="https://github.com/user-attachments/assets/ac5a2eec-a709-4f10-bf82-6058cb486f42">

**Desktop (please provide the following information):**
 - Operating System: [e.g. Ubuntu 20.04]
 - Python 3.10
- Library versions: installed the library using pip3. Here's the versions of the main packages in below:
- pytorch-lightning==2.3.3
- torch==2.5.1
- transformers==4.46.3

**Comment by tanganke** [comment]
Just update the config files to add `_target_`

https://github.com/tanganke/fusion_bench/blob/299a481bb250b9730b5a796f1104dd07bab662b3/config/nyuv2_config.yaml#L9-L10

Please attempt to pull the latest updates from the main branch.

**Comment by tanganke** [comment]
The checkpoints I used were missing, you can finetune some single-task models using `fusion_bench/scripts/nyuv2_mtl_train.py`. The run command would be:

```bash
python fusion_bench/scripts/nyuv2_mtl_train.py
```

Put raw data in `.cache` directory, as follows:

<img width="277" alt="image" src="https://github.com/user-attachments/assets/07da995c-c8c6-4f4e-b6fe-219b1b00b0e1">

The training config is `config/nyuv2_mtl_train.yaml`.
You can perform single-task training as follows:

```yaml
tasks:
  - segmentation
task_weights:
  - 1
```

**Comment by tanganke** [comment]
If you encounter any other issues, feel free to reach me.

**Comment by tanganke** [comment]
Download raw data from this link: https://cloud.tsinghua.edu.cn/f/6d0a89f4ca1347d8af5f/?dl=1
